# -*- coding: utf-8 -*-
"""221_lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otNBmIZCIxAz2IigK7wpHvZHQXWyaSUn
"""

# task-1--01
inp= open('/content/drive/MyDrive/Colab Notebooks/221_lab2/lab2_input1_1.txt', 'r')
out= open('/content/drive/MyDrive/Colab Notebooks/221_lab2/lab2_output1_1.txt', 'w')

t= inp.readline().strip().split(' ')
sum= int(t[1])
l= inp.readline().strip().split(' ')

nums=[]
for i in range(len(l)):
  nums.append(int(l[i]))

for i in range(len(nums)):
  for j in range(len(nums)):
    if (sum- nums[i]) in nums:
      if nums[j]==(sum-nums[i]):
        output= str(i+1)+' '+ str(j+1)
        out.write(output)
    break
  out.write('impossible')

# task-1--02
inp= open('/content/drive/MyDrive/Colab Notebooks/221_lab2/lab2_input1_1.txt', 'r')
out= open('/content/drive/MyDrive/Colab Notebooks/221_lab2/lab2_output1_2.txt', 'w')

t= inp.readline().strip().split(' ')
sum= int(t[1])
l= inp.readline().strip().split(' ')

nums=[]
for i in range(len(l)):
  nums.append(int(l[i]))

def index(n):
  for i in range(len(nums)):
    if nums[i]==n:
      return i

for i in range(len(nums)):
  if (sum- nums[i]) in nums:
    p= index(sum-nums[i])
    output= str(i+1)+' '+ str(p+1)
    out.write(output)
    break
  out.write('impossible')

# # Task-2--02
# inp= open('/content/drive/MyDrive/Colab Notebooks/221_lab2/lab2_input2_1.txt', 'r')
# out= open('/content/drive/MyDrive/Colab Notebooks/221_lab2/lab2_output2_1.txt', 'w')

# N=[]

# t= inp.readline()

# a1= inp.readline().strip().split(' ')
# for i in range(len(a1)):
#   N.append(int(a1[i]))

# p= inp.readline()

# a2= inp.readline().strip().split(' ')
# for i in range(len(a2)):
#   N.append(int(a2[i]))

# N.sort()
# N

# Task-2--02
inp= open('/content/drive/MyDrive/Colab Notebooks/221_lab2/lab2_input2_2.txt', 'r')
out= open('/content/drive/MyDrive/Colab Notebooks/221_lab2/lab2_output2_2.txt', 'w')

arr=[]

t= inp.readline()

arr1=[]
a1= inp.readline().strip().split(' ')
for i in range(len(a1)):
  arr1.append(int(a1[i]))

p= inp.readline()

arr2=[]
a2= inp.readline().strip().split(' ')
for i in range(len(a2)):
  arr2.append(int(a2[i]))

i,j,k=0,0,0
arr=[]

while len(arr)<=k:
  if i==len(arr1) and j==len(arr2):
    break
  if arr1[i]<arr2[j]:
    arr.append(arr1[i])
    i+=1
    k+=1
    if i==len(arr1) and j<len(arr2):
      arr+= arr2[j:]
  else:
    arr.append(arr2[j])
    j+=1
    k+=1
    if j==len(arr2) and i<len(arr1):
      arr+= arr1[i:]
out.write(str(arr))

# task-03
inp= open('/content/drive/MyDrive/Colab Notebooks/221_lab2/lab2_input3.txt', 'r')
out= open('/content/drive/MyDrive/Colab Notebooks/221_lab2/lab2_output3.txt', 'w')

t= inp.readline()
nums= inp.readline().strip().split(' ')

num=[]
for i in range(len(nums)):
  num.append(int(nums[i]))