# -*- coding: utf-8 -*-
"""221_lab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mdYcO4cvkD63qVCUTKiUjZ6dWoTIzoxB
"""

# task-1(a)
inp= open('/content/drive/MyDrive/Colab Notebooks/221_lab4/lab4_input1a_1.txt', 'r')
out= open('/content/drive/MyDrive/Colab Notebooks/221_lab4/lab4_output1a_1.txt', 'w')

n, m= map(int, inp.readline().split(' '))

lst= [[0 for i in range(n+1)] for i in range(n+1)]

for i in range(m):
  u, v, w = map(int, inp.readline().split(' '))
  lst[u][v]= w

end= ' '
for i in lst:
  for j in i:
    out.write(f'{j} {end}')
  out.write(f'\n')

inp.close()
out.close()

# task-1(b)
inp =open('/content/drive/MyDrive/Colab Notebooks/221_lab4/lab4_input1a_1.txt', 'r')
out= open('/content/drive/MyDrive/Colab Notebooks/221_lab4/lab4_output1b_1.txt', 'w')

n, m= map(int, inp.readline().split(' '))

lst= [[] for i in range(n+1)]

for i in range(m):
  u, v, w = map(int, inp.readline().split(' '))
  lst[u].append((v,w))
end= ' '

for i in range(n + 1):
  out.write(f"{i}: {end}")
  for j in lst[i]:
    out.write(f'{j} {end}')
  out.write(f'\n')

inp.close()
out.close()