# -*- coding: utf-8 -*-
"""221_lab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15bVK-TD9P5MpKuRrN5c9yOPICM3jmEFV
"""

inp= open('/content/drive/MyDrive/Colab Notebooks/221_lab1_input1a.txt', 'r')
out= open('/content/drive/MyDrive/Colab Notebooks/221_lab1_output1a.txt', 'w')

t= inp.readline()

for i in range(0,int(t)):
  newline= '\n'
  current_number= inp.readline().strip()
  if i==int(t)-1:
    newline= ''
  if int(current_number)%2==0:
    out.write(f"{current_number} is an even number.{newline}")
  else:
    out.write(f"{current_number} is an odd number.{newline}")

inp.close()
out.close()

inp= open('/content/drive/MyDrive/Colab Notebooks/221_lab1_input1b.txt', 'r')
out= open('/content/drive/MyDrive/Colab Notebooks/221_lab1_output1b.txt', 'w')

t= inp.readline()

for i in range(0, int(t)):
  numbers= inp.readline().replace('calculate ', '').strip()
  newline= '\n'
  if i== int(t)-1:
    newline= ' '
  for i in range(0, len(numbers)):

    if numbers[i]=='+':
      num1, num2= numbers.split('+')
      result= int(num1)+ int(num2)
      out.write(f"The result of {numbers} is {result} {newline}")

    elif numbers[i]=='-':
      num1, num2= numbers.split('-')
      result= int(num1)- int(num2)
      out.write(f"The result of {numbers} is {result} {newline}")

    elif numbers[i]=='*':
      num1, num2= numbers.split('*')
      result= int(num1)* int(num2)
      out.write(f"The result of {numbers} is {result} {newline}")

    elif numbers[i]=='/':
      num1, num2= numbers.split('/')
      result= int(num1)/ int(num2)
      out.write(f"The result of {numbers} is {result} {newline}")

inp.close()
out.close()

inp= open('/content/drive/MyDrive/Colab Notebooks/221_lab1_input2.txt', 'r')
out= open('/content/drive/MyDrive/Colab Notebooks/221_lab1_output2.txt', 'w')
 
t= inp.readline()
a= inp.readline()

arr= a.split(' ')
arr = [int(i) for i in arr]

def bubbleSort(arr):
  for i in range(len(arr)-1):
    flag= False

    for j in range(len(arr)-i-1):
      if arr[j]> arr[j+1]:
        arr[j], arr[j+1] = arr[j+1], arr[j]
        flag= True 

    if flag==False:
      break  

  return arr

bubbleSort(arr)
x=''
for i in range(len(arr)):
  x= x+ str(arr[i])+ " "
  out.write(x)

inp.close()
out.close()

inp= open('/content/drive/MyDrive/Colab Notebooks/221_lab1_input3.txt', 'r')
out= open('/content/drive/MyDrive/Colab Notebooks/221_lab1_output3.txt', 'w')

t= inp.readline()
id= inp.readline()
mark= inp.readline()

id= id.split(' ')
id = [int(i) for i in id]

mark= mark.split(' ')
mark = [int(i) for i in mark]

for i in range(len(id)):
  for j in range(len(mark)):
    maxi = mark[j]
    max_i = j
    for k in range(j+1, len(mark)):
      if mark[k]>maxi:
        maxi = mark[k]
        max_i = k
      if mark[k]== mark[k-1]:
        if id[k]<id[k-1]:
          id[k-1], id[k]= id[k], id[k-1]
    mark[max_i], mark[j]= mark[j], mark[max_i]
    id[max_i], id[j]= id[j], id[max_i]

for i in range(len(id)):
  newline= '\n'
  ids= id[i]
  marks= mark[i]
  if i==len(id)-1:
    newline= ''
  out.write(f"ID: {ids} MARK: {marks} {newline}")

inp.close()
out.close()

inp= open('/content/drive/MyDrive/Colab Notebooks/221_lab1_input4.txt', 'r')
out= open('/content/drive/MyDrive/Colab Notebooks/221_lab1_output4.txt', 'w')

t= inp.readline()

for i in range(0, int(t)):
  newline= '\n'
  if i==int(t)-1:
    newline= ''
  name= list(inp.readline().strip().split(' ')[0])